<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-A2U9APN6" failures="1" tests="2" name="Updating_Resume" time="77.207" errors="0" timestamp="2024-08-31T13:10:17 IST">
  <testcase classname="All_Flows.Update_Resume_Noukary" name="updating_Noukary_Resume" time="34.521"/>
  <testcase classname="All_Flows.Update_Resume_foundit" name="updating_Foundit_Resume" time="42.511">
    <failure type="java.lang.RuntimeException" message="Test failed because the popup message did not contain &amp;apos;Successfully&amp;apos;.">
      <![CDATA[java.lang.RuntimeException: Test failed because the popup message did not contain 'Successfully'.
at All_Flows.Update_Resume_foundit.updating_Foundit_Resume(Update_Resume_foundit.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- updating_Foundit_Resume -->
</testsuite> <!-- Updating_Resume -->
